Documentation expansion
mlederbauer/NMRcraft pull request #17
Opened 2024-04-16 14:24 UTC by tiaguinho-code

# Docs
Added a step by step type tutorial to Docker and how to basically ideally use the development environment in Readme. Also removed some stuff that was deemed unnecessary.

2024-04-16 21:04 UTC, mlederbauer requested changes
Hi Tiago I am not sure if I understood the structure of the new README correctly? Why are we deleting the ## App and ## Poster or moving it to the bottom of the document, respectively? I would strongly vouch for keeping the referneces to the web demo and poster at the top of the document, this should 100% be what the user sees first. The sections ## Usage, ## App, ## Poster should be at the top of the README and are intended to be a WIP until the end of the project. Everything we need for developing right now (Docker etc) should be in ## Developing at the bottom of the README.
Please let me know if I missed something.

2024-04-16 21:04 UTC, mlederbauer commented on README.md
> -## 👩‍💻 App
Please don’t delete this! the App and Posters will be dispayed under the heading in the end :-(. I would storngly suggest to keep the structure of the headings (with the #TODOS, if necessary, because it is still to do).

2024-04-16 21:04 UTC, mlederbauer commented on README.md
> -Run the app demo locally with
Same here, kindly leave the instructions for running the app and showing the poster as-is. Except for if there is a strong reason you want to delete this section on the demo. I strongly lean against it.

2024-04-16 21:04 UTC, mlederbauer commented on README.md
> -python nmrcraft/app.py
Please leave this in there, it is the cmd to run the web app

2024-04-16 21:04 UTC, mlederbauer commented on README.md
> -## 🖼️Poster
Please leave this in there, we will display the poster here in the end.

2024-04-16 21:04 UTC, mlederbauer commented on README.md
> -## 🧑‍💻 Developing
Please leave this heading here, there should be the sections

## Usage
- how to run the cmd and what the package can do (WIP until end of the project)
## App
- web demo insructions (WIP until later this month)
## Poster
- WIP until end of project
## Developing
- here and only here should we keep the instructions for using Docker in VSCode and verything we need RIGHT NOW for developing & contributing.

2024-04-16 21:04 UTC, mlederbauer commented on README.md
> -make install
Please leave the make install except for if there is a strong reason to not use make install.

2024-04-17 07:15 UTC, tiaguinho-code commented on README.md
> -## 🧑‍💻 Developing
Ah alright, I misunderstood the Use part

2024-04-17 07:17 UTC, tiaguinho-code commented on README.md
> -Run the app demo locally with
Oh no, it only shows as deleted as it was moved down. It's still there

2024-04-17 07:19 UTC, tiaguinho-code commented on README.md
> -make install
As I understand it, the docker is handling the installation of the project. I guess it doesn't matter too much so we can just default to the make i stall then

2024-04-17 07:20 UTC, tiaguinho-code reviewed
Gonna fix the structure according to your instruction

2024-04-17 07:38 UTC, mlederbauer commented
Thank you so much!

2024-04-17 07:39 UTC, mlederbauer commented on README.md
> -make install
Ok perfect, thank you! We can also delete the makefile altogether if you think that’s better, but what I appreciate about a makefile is is that multiple commands are handled “under the hood"

2024-04-17 07:41 UTC, mlederbauer commented
If we just put the Docker Stuff to the development instructions, and put the other headings on top, it works perfectly!

2024-04-17 09:31 UTC, tiaguinho-code commented on README.md
> -make install
Nah, deleting the makefile doesn't sound good as it handles more than just the installation. Thing is that the installation is handled by the Image but I guess the Make install command can also be used when experimenting around and adding new packages, so we definetly want to leave it in.

2024-04-17 19:07 UTC, mlederbauer commented
Does this documentation work for you? @tiaguinho-code I essentially, as you suggested, put the Docker instructions to “developing” instead of “usage"

2024-04-17 19:49 UTC, tiaguinho-code commented
> Does this documentation work for you? @tiaguinho-code I essentially, as you suggested, put the Docker instructions to “developing” instead of “usage"

Yes, looks good to me

2024-04-17 19:59 UTC, mlederbauer approved these changes

2024-04-17 19:59 UTC, merged