Chore/docstrings
mlederbauer/NMRcraft pull request #88
Opened 2024-06-13 13:50 UTC by tiaguinho-code

Adding docstrings to all functions in nmrcraft directory and also added the poster to the readme.

2024-06-13 13:50 UTC, tiaguinho-code commented
Poster is 1000DPI so 8MB. Maybe that's a bit chunky, we can have different resolutions and you guys decide whats best for the readme experience

2024-06-14 12:25 UTC, mlederbauer requested changes
Super nice work, thanks a lot Tiago! Particularly the examples are very nice to add to the dataloader docstring. I think it’s good to go, however there were two things that would be good to address before merging

(i) Poster resolution: Is there a particular reason we save the poster in multiple resolutions?

(ii) Visualizer and Classifier: Do we call these modules/python files in our workflow? If I remember correctly, we implemented all functionality of those files in our code, but do not need the file itself anymore. Could you kindly check if we “need” the Visualizer/Classifier for running the code and, if not, delete them? Just to not cause any confusion when the TAs review the code.

Thanks a lot in advance!!

2024-06-14 12:25 UTC, mlederbauer commented on README.md
> +If you were not able to visit our beautiful poster at ETH Zurich on May 30th 2024, you can access our poster [here](assets/Poster.pdf)!
Thanks a lot for taking care of this!

2024-06-14 12:25 UTC, mlederbauer commented on assets/Poster_100dpi.png
Do we need the poster in the other resolutions?

2024-06-14 12:25 UTC, mlederbauer commented on nmrcraft/data/dataloader.py
> +    """
Super nice very clean and explanatory docstrings!

2024-06-14 12:25 UTC, mlederbauer commented on nmrcraft/evaluation/visualizer.py
Do we even need the visualizer anymore or is it depreceated, since we running the visualization via `scripts/visualize_results`?

2024-06-14 12:25 UTC, mlederbauer commented on nmrcraft/evaluation/visualizer.py
If it is not needed anymore, I would suggest to delete the file for keeping a better overview

2024-06-14 12:25 UTC, mlederbauer commented on nmrcraft/evaluation/visualizer.py
The only plotting function we use in `visualize_results` are those from `nmrcraft/analysis/plotting`

2024-06-14 12:25 UTC, mlederbauer commented on nmrcraft/models/classifier.py
Same here, I very much appreciate the awesome overview of the module with the docstirngs and explanations, but isn’t this depreciated, as we are not calling the Classifier in `scripts/training/one_target.py` or `multiple_targets.py` anymore?

2024-06-14 12:25 UTC, mlederbauer commented on nmrcraft/utils/general.py
Very nicew, one option would be to rename this file to dataframe , dataframe_utils or something else? BUt this is completely optional

2024-06-15 11:22 UTC, mlederbauer commented
Could you kindly select the poster resolution that we need (@kbiniek ), after that we can merge to main. Thanks a lot in advance !!

2024-06-19 08:40 UTC, tiaguinho-code commented on nmrcraft/evaluation/visualizer.py
I'd suggest only starting to delete stuff once we're fully there with a working reproduce script and do all the deleting in a deletion PR (just in case)

2024-06-19 08:40 UTC, tiaguinho-code commented on nmrcraft/models/classifier.py
not sure, just went all out

same here as above where I'd like to keep stuff until the very end

2024-06-19 11:41 UTC, mlederbauer approved these changes
LEt’s remove the redundant scripts later.

2024-06-19 11:41 UTC, merged